### ISSUE TITLE
The reason: clusterIP: None

### ISSUE THREAD

**Issue by iamnogada** [ausov/k8s-mariadb-cluster#4]
Thanks for the sample and explanation first.

I just tired to expose the mysql client port  using cluster IP with external ip or nodePort,
but there is an error in run musqld : cannot open /var/run/mysqld/mysqld.sock

Is there any reason to make this service as headless?

**Comment by iamnogada** [comment]
Error message is " Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock"
When service type : NodePort

is there any way to access statefulset from outside of cluster
in order to design database and debugging ?

**Comment by ausov** [comment]
You can expose a service with `kubectl expose`. 

Another option is to provide external IP for a service. For example, when running in Minikube with IP 192.168.99.100:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql
  externalIPs: [192.168.99.100]
  selector:
    app: mysql
```
 
This will create a service reachable on 192.168.99.100:3306 from your computer.
